print("Hey, what's your first name? :")
first_name = input().strip()
print("And your last name? :")
last_name = input().strip()
print("Well, pleased to meet you,"+ " " + first_name + " " + last_name + ".")